ALTER TABLE [dbo].[user]
    ADD CONSTRAINT [ak_ak_user_name_uniqu_user] UNIQUE NONCLUSTERED ([user_name] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

