ALTER TABLE [dbo].[netsqlazman_StorePermissionsTable]
    ADD CONSTRAINT [PK_StorePermissions] PRIMARY KEY CLUSTERED ([StorePermissionId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

