ALTER TABLE [dbo].[netsqlazman_ApplicationGroupMembersTable]
    ADD CONSTRAINT [PK_GroupMembers] PRIMARY KEY CLUSTERED ([ApplicationGroupMemberId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

