ALTER TABLE [dbo].[netsqlazman_Settings]
    ADD CONSTRAINT [PK_Settings] PRIMARY KEY CLUSTERED ([SettingName] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

