ALTER TABLE [dbo].[application_option]
    ADD CONSTRAINT [pk_application_option] PRIMARY KEY CLUSTERED ([option_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

