ALTER TABLE [dbo].[netsqlazman_ItemAttributesTable]
    ADD CONSTRAINT [PK_ItemAttributes] PRIMARY KEY CLUSTERED ([ItemAttributeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

