ALTER TABLE [dbo].[user_option_value]
    ADD CONSTRAINT [pk_user_option_value] PRIMARY KEY CLUSTERED ([value_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

