ALTER TABLE [dbo].[netsqlazman_LogTable]
    ADD CONSTRAINT [PK_Log] PRIMARY KEY NONCLUSTERED ([LogId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

