ALTER TABLE [dbo].[netsqlazman_BizRulesTable]
    ADD CONSTRAINT [PK_BizRules] PRIMARY KEY CLUSTERED ([BizRuleId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

