ALTER TABLE [dbo].[netsqlazman_StoreGroupMembersTable]
    ADD CONSTRAINT [PK_StoreGroupMembers] PRIMARY KEY CLUSTERED ([StoreGroupMemberId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

