ALTER TABLE [dbo].[netsqlazman_ItemsHierarchyTable]
    ADD CONSTRAINT [PK_ItemsHierarchy] PRIMARY KEY CLUSTERED ([ItemId] ASC, [MemberOfItemId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

