ALTER TABLE [dbo].[company_information]
    ADD CONSTRAINT [pk_company_information] PRIMARY KEY CLUSTERED ([company_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

