ALTER TABLE [fixedasset].[custodian_asset]
    ADD CONSTRAINT [pk_assign_custodian] PRIMARY KEY CLUSTERED ([record_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

