ALTER TABLE [fixedasset].[depreciation]
    ADD CONSTRAINT [pk_depreciation] PRIMARY KEY CLUSTERED ([depreciation_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

