ALTER TABLE [fixedasset].[asset]
    ADD CONSTRAINT [pk_item] PRIMARY KEY CLUSTERED ([asset_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

