ALTER TABLE [fixedasset].[custodian]
    ADD CONSTRAINT [pk_custodian] PRIMARY KEY CLUSTERED ([custodian_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

