ALTER TABLE [hrm].[job_function]
    ADD CONSTRAINT [pk_job_function] PRIMARY KEY CLUSTERED ([job_function_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

