ALTER TABLE [hrm].[job]
    ADD CONSTRAINT [pk_job] PRIMARY KEY CLUSTERED ([job_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

