ALTER TABLE [hrm].[employee_acting_promotion]
    ADD CONSTRAINT [pk_acting_promotion] PRIMARY KEY CLUSTERED ([acting_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

