ALTER TABLE [hrm].[marital_status]
    ADD CONSTRAINT [pk_marital_status] PRIMARY KEY CLUSTERED ([marital_status_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

