ALTER TABLE [hrm].[employee_insurance]
    ADD CONSTRAINT [pk_employee_insurance] PRIMARY KEY CLUSTERED ([insurance_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

