ALTER TABLE [hrm].[deduction_condition]
    ADD CONSTRAINT [pk_deduction_condition] PRIMARY KEY CLUSTERED ([condition_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

