ALTER TABLE [hrm].[training_category]
    ADD CONSTRAINT [PK_training_category] PRIMARY KEY CLUSTERED ([training_category_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

