ALTER TABLE [hrm].[employee_transfer]
    ADD CONSTRAINT [PK_employee_transfer] PRIMARY KEY CLUSTERED ([transfer_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

