ALTER TABLE [hrm].[ethnicity]
    ADD CONSTRAINT [pk_ethnicity] PRIMARY KEY CLUSTERED ([ethnicity_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

