ALTER TABLE [hrm].[bank_branch]
    ADD CONSTRAINT [pk_bank_branch] PRIMARY KEY CLUSTERED ([bank_branch_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

