ALTER TABLE [hrm].[country]
    ADD CONSTRAINT [pk_country] PRIMARY KEY CLUSTERED ([country_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

