ALTER TABLE [hrm].[religion]
    ADD CONSTRAINT [pk_religion] PRIMARY KEY CLUSTERED ([religion_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

