ALTER TABLE [hrm].[employee_skill_type]
    ADD CONSTRAINT [pk_skill_measure_type] PRIMARY KEY CLUSTERED ([skill_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

