ALTER TABLE [hrm].[certificate]
    ADD CONSTRAINT [pk_certificate] PRIMARY KEY CLUSTERED ([certificate_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

