ALTER TABLE [hrm].[employee_accident]
    ADD CONSTRAINT [pk_accident] PRIMARY KEY CLUSTERED ([accident_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

