ALTER TABLE [hrm].[employee_skill]
    ADD CONSTRAINT [pk_employee_skill] PRIMARY KEY CLUSTERED ([employee_skill_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

