ALTER TABLE [hrm].[employee_dependant]
    ADD CONSTRAINT [pk_dependant] PRIMARY KEY CLUSTERED ([dependant_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

