ALTER TABLE [hrm].[leave_type]
    ADD CONSTRAINT [PK_leave_type] PRIMARY KEY CLUSTERED ([leave_type_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

