ALTER TABLE [hrm].[training_request]
    ADD CONSTRAINT [PK_training_request] PRIMARY KEY CLUSTERED ([training_request_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

