ALTER TABLE [hrm].[job_skill_type]
    ADD CONSTRAINT [pk_job_skill_type] PRIMARY KEY CLUSTERED ([skill_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

