ALTER TABLE [hrm].[language_skill]
    ADD CONSTRAINT [pk_language_skill] PRIMARY KEY CLUSTERED ([language_skill_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

