ALTER TABLE [hrm].[insurance_policy_type]
    ADD CONSTRAINT [pk_insurance_policy_type] PRIMARY KEY CLUSTERED ([policy_type_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

