ALTER TABLE [hrm].[training_attendance]
    ADD CONSTRAINT [PK_training_attendance] PRIMARY KEY CLUSTERED ([training_atendant_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

