ALTER TABLE [hrm].[employee_type]
    ADD CONSTRAINT [pk_employeecatagory] PRIMARY KEY CLUSTERED ([employement_type_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

