ALTER TABLE [hrm].[education_level]
    ADD CONSTRAINT [pk_education_level] PRIMARY KEY CLUSTERED ([education_level_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

