/*ALTER TABLE [hrm].[warning_type]
    ADD CONSTRAINT [PK_warning_type] PRIMARY KEY CLUSTERED ([warning_type_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

