/*ALTER TABLE [hrm].[contact]
    ADD CONSTRAINT [pk_address] PRIMARY KEY CLUSTERED ([address_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

