ALTER TABLE [hrm].[appraisal]
    ADD CONSTRAINT [pk_appraisal] PRIMARY KEY CLUSTERED ([appraisalid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

