/*ALTER TABLE [hrm].[benefit]
    ADD CONSTRAINT [pk_benefit] PRIMARY KEY CLUSTERED ([benefit_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

