ALTER TABLE [hrm].[emergency_contact]
    ADD CONSTRAINT [pk_emergency_contact] PRIMARY KEY CLUSTERED ([contact_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

