ALTER TABLE [hrm].[employee]
    ADD CONSTRAINT [pk_employee] PRIMARY KEY CLUSTERED ([employee_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

