/*ALTER TABLE [hrm].[employee_leave]
    ADD CONSTRAINT [pk_employee_leave] PRIMARY KEY CLUSTERED ([employee_leave_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

