/*ALTER TABLE [hrm].[leave_request]
    ADD CONSTRAINT [pk_leave_request] PRIMARY KEY CLUSTERED ([emp_employee_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

