ALTER TABLE [fleet].[route_job]
    ADD CONSTRAINT [ak_job_name_unq_key_route_jo] UNIQUE NONCLUSTERED ([job_name] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

