ALTER TABLE [fleet].[route_fuel_log]
    ADD CONSTRAINT [pk_route_fuel_log] PRIMARY KEY CLUSTERED ([route_id] ASC, [fuel_log_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

