ALTER TABLE [fleet].[route]
    ADD CONSTRAINT [pk_route] PRIMARY KEY CLUSTERED ([route_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

