ALTER TABLE [fleet].[vehicle]
    ADD CONSTRAINT [pk_vehicle] PRIMARY KEY CLUSTERED ([vehicle_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

