/*ALTER TABLE [fleet].[tire_type]
    ADD CONSTRAINT [ak_tire_name_unique_k_tire_typ] UNIQUE NONCLUSTERED ([name] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];*/

