ALTER TABLE [fleet].[coupon]
    ADD CONSTRAINT [pk_coupon] PRIMARY KEY CLUSTERED ([coupon_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

