ALTER TABLE [fleet].[driver]
    ADD CONSTRAINT [pk_driver] PRIMARY KEY CLUSTERED ([driver_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

