ALTER TABLE [fleet].[fuel_station]
    ADD CONSTRAINT [pk_fuel_station] PRIMARY KEY CLUSTERED ([fuel_station_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

