ALTER TABLE [fleet].[insurance_history]
    ADD CONSTRAINT [pk_insurance_history] PRIMARY KEY CLUSTERED ([history_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

