ALTER TABLE [fleet].[maintenance_activity]
    ADD CONSTRAINT [pk_maintenance_activity] PRIMARY KEY CLUSTERED ([activity_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

