ALTER TABLE [fleet].[maintanance]
    ADD CONSTRAINT [pk_maintanance] PRIMARY KEY CLUSTERED ([maintenance_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

