ALTER TABLE [fleet].[order_type]
    ADD CONSTRAINT [pk_order_type] PRIMARY KEY CLUSTERED ([order_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

