ALTER TABLE [stock].[issue_detail]
    ADD CONSTRAINT [pk_issue_detail] PRIMARY KEY CLUSTERED ([issue_detail_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

