ALTER TABLE [stock].[warehouse]
    ADD CONSTRAINT [pk_warehouse] PRIMARY KEY CLUSTERED ([warehouse_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

