ALTER TABLE [stock].[sequence_counter]
    ADD CONSTRAINT [pk_sequence_counter] PRIMARY KEY CLUSTERED ([record_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

