ALTER TABLE [stock].[measurement_unit]
    ADD CONSTRAINT [pk_measurement_unit] PRIMARY KEY CLUSTERED ([unit_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

