ALTER TABLE [stock].[sub_category]
    ADD CONSTRAINT [pk_sub_category] PRIMARY KEY CLUSTERED ([sub_category_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

