ALTER TABLE [stock].[return]
    ADD CONSTRAINT [pk_return] PRIMARY KEY CLUSTERED ([return_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

