ALTER TABLE [stock].[stock_status]
    ADD CONSTRAINT [PK_stock_status] PRIMARY KEY CLUSTERED ([item_id] ASC, [warehouse_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

