ALTER TABLE [stock].[supplier]
    ADD CONSTRAINT [pk_supplier] PRIMARY KEY CLUSTERED ([supplier_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

