ALTER TABLE [stock].[issue]
    ADD CONSTRAINT [pk_issue] PRIMARY KEY CLUSTERED ([issue_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

