ALTER TABLE [wms].[customer]
    ADD CONSTRAINT [pk_customer] PRIMARY KEY CLUSTERED ([customer_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

