ALTER TABLE [wms].[equipment_expiration]
    ADD CONSTRAINT [PK_equipment_expiration] PRIMARY KEY CLUSTERED ([expiration_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

