ALTER TABLE [wms].[equipment]
    ADD CONSTRAINT [pk_equipment] PRIMARY KEY CLUSTERED ([equipment_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

