ALTER TABLE [wms].[equipment_insurance]
    ADD CONSTRAINT [pk_equipment_insurance] PRIMARY KEY CLUSTERED ([insurance_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

