ALTER TABLE [wms].[insurance_company]
    ADD CONSTRAINT [pk_insurance_company] PRIMARY KEY CLUSTERED ([company_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

