ALTER TABLE [wms].[lookup_item]
    ADD CONSTRAINT [PK_lookup_item_1] PRIMARY KEY CLUSTERED ([item_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

