ALTER TABLE [wms].[maintenance_labour]
    ADD CONSTRAINT [pk_maintenance_labour] PRIMARY KEY CLUSTERED ([labour_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

