ALTER TABLE [wms].[miscellaneous_items]
    ADD CONSTRAINT [PK_miscellaneous_items] PRIMARY KEY CLUSTERED ([mis_part_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

