ALTER TABLE [wms].[maintenance_task]
    ADD CONSTRAINT [pk_maintenance_task] PRIMARY KEY CLUSTERED ([task_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

