ALTER TABLE [wms].[pm_schedule]
    ADD CONSTRAINT [pk_pm_schedule] PRIMARY KEY CLUSTERED ([pm_schedule_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

