/*ALTER TABLE [wms].[pm_service_part]
    ADD CONSTRAINT [PK_pm_service_part] PRIMARY KEY CLUSTERED ([pm_part_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

