/*ALTER TABLE [wms].[payment_record]
    ADD CONSTRAINT [PK_payment_recived] PRIMARY KEY CLUSTERED ([payment_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

