ALTER TABLE [wms].[part]
    ADD CONSTRAINT [pk_part] PRIMARY KEY CLUSTERED ([part_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

