ALTER TABLE [wms].[vendor]
    ADD CONSTRAINT [pk_vendor] PRIMARY KEY CLUSTERED ([vendor_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

