ALTER TABLE [payroll].[payroll_setting]
    ADD CONSTRAINT [pk_payroll_setting] PRIMARY KEY CLUSTERED ([setting_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

