ALTER TABLE [payroll].[payroll_information]
    ADD CONSTRAINT [PK_payroll_information] PRIMARY KEY CLUSTERED ([record_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

