ALTER TABLE [payroll].[payroll_parameter]
    ADD CONSTRAINT [pk_payoll_parameter] PRIMARY KEY CLUSTERED ([param_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

