ALTER TABLE [payroll].[payroll_cost_center]
    ADD CONSTRAINT [pk_payroll_cost_center] PRIMARY KEY CLUSTERED ([cost_center_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

